### ISSUE TITLE
大佬，这个怎么用啊，没明白

### ISSUE THREAD

**Issue by malone6** [moshowgame/dbeaver-driver-all#3]
我的dbeaver死活下载不了驱动，按网上的配置改了maven为阿里云也下载不了（此间dbeaver还一直卡死，崩溃）。
这些文件是一次性放到某个地方就能自动识别吗？

**Comment by moshowgame** [comment]
https://blog.csdn.net/moshowgame/article/details/107225203

可以设置离线驱动地址

![image](https://user-images.githubusercontent.com/3946315/204080788-b956353e-4180-4988-a670-550ea9f6a9d9.png)

**Comment by malone6** [comment]
看了这篇文章，也试了还是不行。不做java对java-maven这套机制不理解，但是按着文档操作，有图中4个疑问（当然最后也没能达到离线使用）
![image](https://user-images.githubusercontent.com/15245112/204183355-9a02883d-6825-47af-97af-cc3e83904e95.png)


![image](https://user-images.githubusercontent.com/15245112/204183266-73ea4122-4c33-45e2-b970-bdf2dc7a821e.png)

大佬能不能在解答下

**Comment by malone6** [comment]
@moshowgame 已看到文档的更新，写的非常清楚，感谢
